# Generated by Django 3.1.5 on 2021-02-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0005_subscription_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.subscription')),
            ],
        ),
    ]
