# Generated by Django 3.1.5 on 2021-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=6),
            preserve_default=False,
        ),
    ]
