# Generated by Django 3.1.5 on 2021-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
