# Generated by Django 3.1.5 on 2021-02-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_sku'),
        ('signup', '0002_subscriptiondetails_subscription_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiondetails',
            options={'verbose_name_plural': 'Subscription details'},
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='subscription_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
