# Generated by Django 3.1.5 on 2021-02-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_category_friendly_name'),
        ('signup', '0003_signup_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='subscription_plan',
        ),
        migrations.CreateModel(
            name='SignupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
            ],
        ),
    ]
