# Generated by Django 3.1.5 on 2021-02-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_sku'),
        ('signup', '0003_auto_20210217_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
