# Generated by Django 3.1.5 on 2021-02-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210220_1654'),
        ('signup', '0005_auto_20210218_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='profiles.userprofile'),
        ),
    ]
