# Generated by Django 3.1.5 on 2021-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210202_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='duration',
            field=models.DurationField(),
        ),
    ]
