# Generated by Django 3.1.5 on 2021-02-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210202_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(default='weekly', max_length=254),
            preserve_default=False,
        ),
    ]
